# Schema for the configuration files of the Stark theme.

stark.settings:
  type: theme_settings
  label: 'MichaelTaylor3D settings'

stark.breakpoints:
  type: theme_breakpoints_default
  label: 'MichaelTaylor3D breakpoints'
